#!/bin/bash
#
# Copyright 2015 Brandon Evans
# 
# Based on xode-toggle by Jonathan Wight
# https://github.com/schwa/xcode-toggle
#

set -eo pipefail

xcodes=`find /Applications -type d -maxdepth 1 -name Xcode\*.app -exec basename {} \;`

list_xcodes() {
    local current_xcode_path=`xcode-select -p | cut -d'/' -f-3`
    local current_xcode=`echo "$current_xcode_path" | cut -d'/' -f3-`
    local current_xcode_index=`echo "$xcodes" | grep -n "$current_xcode" | cut -f1 -d:`
    echo "$xcodes" | awk -v i="$current_xcode_index" '{ printf NR ") " $0} i == NR { printf "\033[1;31m" " [CURRENT]" "\033[0m " } { print "" }' 
}

select_xcode_at_index() {
    declare index="$1"
    xcode=$(echo "$xcodes" | tail -n+"$index" | head -n1)
    sudo xcode-select -s "/Applications/$xcode"
}

list_xcodes
read -r -p "Enter a number to select an Xcode: " index
select_xcode_at_index $index
list_xcodes

exit 0

